name: GitHub Package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6.0.9

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: "@rubix-studios-pty-ltd"

      - run: pnpm install --frozen-lockfile

      - run: pnpm test:all

      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
